// Generated from PacketDataEnum.h.handlebars
#pragma once


#include "PacketDataEnum.generated.h"

UENUM(BlueprintType)
enum class ECRUD : uint8
{
	CRUD_FAIL = 0,
	CRUD_OK = 1,
	CRUD_LOGICAL_ERROR = 99,
};

UENUM(BlueprintType)
enum class EPVP : uint8
{
	NONE = 0,
	BG = 1,
	GR = 2,
	CS = 3,
	BF = 4,
	SR = 5,
	MR = 6,
};

UENUM(BlueprintType)
enum class EQUEST : uint8
{
	READY = 0,
	DONE = 1,
	COMPLETE = 2,
};

UENUM(BlueprintType)
enum class EHERO_LEVELUP_MODE : uint8
{
	ONE = 1,
	ALL = 2,
};

UENUM(BlueprintType)
enum class EHERO_SKILL_SLOT : uint8
{
	ActiveSkill01 = 0,
	ActiveSkill02 = 1,
	ActiveSkill03 = 2,
	PassiveSkill01 = 3,
	PassiveSkill02 = 4,
};

UENUM(BlueprintType)
enum class EHERO_ITEM_SLOT : uint8
{
	Weapon = 0,
	Armor = 1,
	Pants = 2,
	Ring = 3,
	Necklace = 4,
};

UENUM(BlueprintType)
enum class EHERO_ENCHANT_STAT_SLOT : uint8
{
	PhysicalAttackPower = 0,
	MagicAttackPower = 1,
	Armor = 2,
	MagicResistance = 3,
	MaxHP = 4,
};

UENUM(BlueprintType)
enum class EPLAY_LOD : uint8
{
	CAMP_NORMAL = 10,
	CAMP_HARD = 11,
	RAID_NORMAL = 20,
	RAID_HARD = 21,
	RAID_NIGHTMARE = 22,
	RAID_HELL = 23,
	ARENA = 30,
	ARENA_BAT = 31,
};

UENUM(BlueprintType)
enum class EPLAY_CAMP_TAB : uint8
{
	CAMP = 10,
	HERO = 20,
	CHALL = 30,
};

UENUM(BlueprintType)
enum class EPLAY_CAMP_REWARD_MODE : uint8
{
	CHAPTER_STAR = 10,
	CHAPTER_CLEAR = 15,
	EPISODE_STAR = 20,
	EPISODE_CLEAR = 35,
};

UENUM(BlueprintType)
enum class EPLAY_CAMP_CONFIG : uint8
{
	CHAPTER_STAR = 10,
	CHAPTER_CLEAR = 15,
	EPISODE_STAR = 20,
	EPISODE_CLEAR = 35,
};

UENUM(BlueprintType)
enum class EPLAY_CLEAR_GRADE : uint8
{
	CLEAR_FAILED = 0,
	CLEAR_STAR_ONE = 1,
	CLEAR_STAR_TWO = 2,
	CLEAR_STAR_THR = 3,
};

UENUM(BlueprintType)
enum class EPLAY_DECK_TYPE : uint8
{
	DECK1 = 0,
	DECK2 = 1,
	DECK3 = 2,
	DECK4 = 3,
};

UENUM(BlueprintType)
enum class EPLAY_DECK_FORMATION : uint8
{
	OFFENSE = 0,
	BALANCE = 1,
	DEFENCE = 2,
	NONE = 99,
};

UENUM(BlueprintType)
enum class EREWARD_TYPE : uint8
{
	NONE = 0,
	ITEM = 1,
	HERO = 2,
	AVATAR_EXP = 3,
	ARENA_POINT = 4,
	PACK = 5,
	COLOSSEUM_POINT = 6,
	BSG = 7,
	TREASURE_MAP = 8,
	TREASURE_KEY = 9,
	WALLET = 10,
	HERO_EXP = 11,
};

UENUM(BlueprintType)
enum class EACHIEVE_TYPE : uint8
{
	AVATAR_LEVEL = 1,
	HERO_GRADE_AGATHON = 2,
	HERO_GRADE_RAYNA = 3,
	HERO_GRADE_THAN = 4,
	HERO_GRADE_SIRIA = 5,
	HERO_GRADE_GRANT = 6,
	HERO_GRADE_ZAGAN = 7,
	HERO_GRADE_FLAME = 8,
	HERO_GRADE_BARTOR = 9,
	HERO_GRADE_YOSEPH = 10,
	HERO_GRADE_AMON = 11,
	HERO_GRADE_MOMENT = 12,
	HERO_GRADE_BALT = 13,
	HERO_GRADE_LUCY = 14,
	HERO_GRADE_SOPHIA = 15,
	HERO_GRADE_RHEA = 16,
	HERO_GRADE_SCARLET = 17,
	HERO_GRADE_JIN = 18,
	HERO_GRADE_PANG = 19,
	HERO_GRADE_TIERA = 20,
	HERO_GRADE_BONNIE = 21,
	HERO_GRADE_IOLA = 22,
	HERO_GRADE_DOROTHY = 23,
	HERO_GRADE_BANTONIO = 24,
	HERO_GRADE_SHARON = 25,
	HERO_GRADE_BARD = 26,
	HERO_GRADE_BUDDY = 27,
	HERO_GRADE_BELITA = 28,
	HERO_GRADE_MURMUR = 29,
	GET_HERO_CNT = 30,
	GET_HERO_GRADE7_CNT = 31,
	GET_HERO_GRADE8_CNT = 32,
	GET_HERO_GRADE9_CNT = 33,
	GET_HERO_GRADE10_CNT = 34,
	GET_SPIRIT_CNT = 35,
	FLOOR_ARRIVE = 36,
	ITEM_RARE_CNT = 37,
	ITEM_EPIC_CNT = 38,
	ITEM_UNIQUE_CNT = 39,
	ITEM_TOWER_CNT = 40,
	ITEM_ENCHANT_CNT = 41,
	ITEM_ENCHANT_SUCCESS = 42,
	ITEM_ENCHANT_FAIL = 43,
	ITEM_ENCHANT_LEVEL = 44,
	ITEM_LEVEL_UP = 45,
	ITEM_LEVEL_MAX_CNT = 46,
	INVEN_GRIND_ITEM_CNT = 47,
	TRY_COLOSSEUM = 48,
	COLOSSEUM_WIN_CNT = 49,
	COLOSSEUM_LOSE_CNT = 50,
	COLOSSEUM_GRADE_DIAMOND1 = 51,
	COLOSSEUM_GRADE_DIAMOND2 = 52,
	COLOSSEUM_GRADE_DIAMOND3 = 53,
	COLOSSEUM_GRADE_DIAMOND4 = 54,
	COLOSSEUM_GRADE_MASTER = 55,
	TRY_ARENA = 56,
	ARENA_WIN_CNT = 57,
	ARENA_LOSE_CNT = 58,
	ARENA_TOP_RANK_RATE = 59,
	ARENA_TOP_RANK = 60,
	ARENA_DEFENCE_CNT = 61,
	JOIN_TO_GUILD = 62,
	CREATE_GUILD = 63,
	HERO_GRIND_CNT = 64,
	ITEM_UPGRADE_CNT = 65,
	PROPERTY_GOLD_VALUE = 66,
	HERO_ENCHANT_CNT = 67,
	HERO_ENCHANT_SUCCESS_CNT = 68,
	HERO_ENCHANT_FAIL_CNT = 69,
};

UENUM(BlueprintType)
enum class EIS_CHECKED : uint8
{
	UNCHECKED = 0,
	CHECKED = 1,
};

UENUM(BlueprintType)
enum class ESHOP_PRODUCT_TYPE : uint8
{
	ITEM = 10,
	GACHA = 20,
	PACK = 30,
	GACHA10 = 40,
};

UENUM(BlueprintType)
enum class ESHOP_ACCESS_TYPE : uint8
{
	EVERYONE = 0,
	VIP = 10,
	LEVEL = 20,
};

UENUM(BlueprintType)
enum class ECOLOSSEUM_CLASS_VAL : uint8
{
	BRONZE_C = 0,
	BRONZE_B = 1,
	BRONZE_A = 2,
	BRONZE_S = 3,
	SILVER_C = 4,
	SILVER_B = 5,
	SILVER_A = 6,
	SILVER_S = 7,
	GOLD_C = 8,
	GOLD_B = 9,
	GOLD_A = 10,
	GOLD_S = 11,
	DIAMOND_C = 12,
	DIAMOND_B = 13,
	DIAMOND_A = 14,
	DIAMOND_S = 15,
	PLATINUM_S = 16,
};

UENUM(BlueprintType)
enum class ECOLOSSEUM_PLAY_TYPE : uint8
{
	NONE = 0,
	TRAINER = 1,
	LEADER = 2,
	CREW = 3,
	TOWER = 4,
	R1 = 5,
	R2 = 6,
	R3 = 7,
	R4 = 8,
	R5 = 9,
};

UENUM(BlueprintType)
enum class EPD_TYPE : uint8
{
	NOTHING = 0,
	NORMAL = 1,
	SYSBOT = 2,
	RESOURCE = 3,
	EVTBOT = 4,
};

UENUM(BlueprintType)
enum class EPD_LOCK_TYPE : uint8
{
	NONE = 0,
	SOFT = 1,
	HARD = 2,
};

UENUM(BlueprintType)
enum class EPD_NPC : uint8
{
	NONE = 0,
	SAVE = 1,
	KILL = 2,
};

UENUM(BlueprintType)
enum class EPD_NPC_TYPE : uint8
{
	Nothing = 0,
	GoblinGold = 1,
	GoblinGem = 2,
	GoblinSweeper = 3,
	GoblinTitan = 4,
	GoblinStamina = 5,
};

UENUM(BlueprintType)
enum class EPD_MINION_TYPE : uint8
{
	SYSTEM = 0,
	SUPPLIED = 1,
	PURCHASED = 2,
};

UENUM(BlueprintType)
enum class EAVATAR_SKILL : uint8
{
	NONE = 0,
	PD_HERO_3 = 1,
	PD_HERO_5 = 2,
};

UENUM(BlueprintType)
enum class EOVERLORD : uint8
{
	TUTORIAL = 1,
	CAMPAIGN = 2,
	CHALLENGE = 3,
	ARENA = 4,
	RAID = 5,
	COLOSSEUM = 6,
	BATTLEFIELD = 7,
	MAIL = 8,
	ITEM_ENCHANT = 9,
	ITEM_MANUFACTURE = 10,
	ITEM_GRIND = 11,
	ITEM_SALE = 12,
	SHOP = 13,
	GUILD = 14,
	HERO_EPISODE = 15,
	BATTLEGROUND_20 = 16,
	BATTLEGROUND_30 = 17,
	BATTLEGROUND_50 = 18,
	ACCOUNT_ABILITY = 19,
	CRUSADER = 20,
};

UENUM(BlueprintType)
enum class EGUILD_GRADE : uint8
{
	MEMBER = 5,
	ELDER = 7,
	MASTER = 10,
};

UENUM(BlueprintType)
enum class EGUILD_CONTRIBUTION_TYPE : uint8
{
	TYPE1 = 1,
	TYPE2 = 2,
	TYPE3 = 3,
};

UENUM(BlueprintType)
enum class EGUILD_HISTORY_TYPE : uint8
{
	JOIN = 1,
	GRADE_UP = 2,
	GRADE_DOWN = 3,
	KICK = 4,
	QUIT = 5,
	CHANGE_NAME = 6,
	CHANGE_INFO = 7,
	LEVEL_UP = 8,
	BOSS_SPAWN = 9,
};

UENUM(BlueprintType)
enum class EREWARDABLE_STATUS : uint8
{
	NOT_READY = 0,
	READY = 1,
	REWARDED = 2,
};

UENUM(BlueprintType)
enum class EENCHANT_RESULT : uint8
{
	FAIL = 0,
	SUCCESS = 1,
	DESTRUCTION = 2,
};

UENUM(BlueprintType)
enum class ECHANNEL_EVENT_TYPE : uint8
{
	PVE = 1,
	PVP = 2,
	GVPVP = 3,
	GVG = 4,
	BOSS_SPAWN = 5,
	GOLD = 6,
	AVATAR_EXP = 7,
	HERO_EXP = 8,
	GEM = 9,
};

UENUM(BlueprintType)
enum class ECOMMUNITY_SORT_TYPE : uint8
{
	RECENT = 0,
	VOTE = 1,
	BEST = 2,
	MINE = 3,
};

UENUM(BlueprintType)
enum class EACCOUNT_LANGUAGE : uint8
{
	VE_KOR = 0,
	VE_ENG = 1,
	VE_CHN = 2,
	VE_TWN = 3,
};

UENUM(BlueprintType)
enum class ECLIENT_SDK_FLAG : uint8
{
	NONE = 0,
	KAKAO_MESSAGE_GET = 1,
};

UENUM(BlueprintType)
enum class ECONTENTS_TYPE : uint8
{
	CAMPAIGN = 1,
	HERO_EPISODE = 2,
	RAID = 3,
	CRUSADER = 4,
	WEEK_DUNGEON = 5,
	COLOSSEUM = 6,
};

UENUM(BlueprintType)
enum class EPREFER_TARGET_TYPE : uint8
{
	NONE = 0,
	TANKER = 1,
	MELEE_DEALER = 2,
	RANGE_DEALER = 3,
	MAGIC_DEALER = 4,
	SUPPORTER = 5,
};

UENUM(BlueprintType)
enum class EMIRROR_TYPE : uint8
{
	PAST = 0,
	PRESENT = 1,
	FUTURE = 2,
};

UENUM(BlueprintType)
enum class ESHOP_FLOORSHOP_SLOT_STATE : uint8
{
	SOLDOUT = 0,
	ENABLED_BUY = 1,
	ENABLED_OPEN = 2,
	DISABLED_FLOOR = 3,
	DISABLED_OPEN = 4,
};

UENUM(BlueprintType)
enum class EINVENTORY_UPGRADE_TYPE : uint8
{
	ITEM = 0,
	HERO = 1,
};

UENUM(BlueprintType)
enum class EFLOOR_MISSION_CLASS_CONDITION_TYPE : uint8
{
	TANKER = 0,
	MELEEDEALER = 1,
	RANGEDEALER = 2,
	SUPPORTER = 5,
	MAGICDEALER = 6,
	NONE = 99,
};

UENUM(BlueprintType)
enum class EWALLET_TYPE1 : uint8
{
	NONE = 0,
	GOLD = 1,
	GEM = 2,
	MILEAGE = 3,
	SPIRIT_STONE = 4,
	HERO_RUNE = 5,
	GUILD_RAID_POINT = 6,
	REDSTONE = 7,
	PVPTOKEN = 8,
	BGT1 = 9,
	BGT2 = 10,
	BGT3 = 11,
	STAMINA = 12,
	STAMINA_PVP = 13,
	ENCHANTSCROLL_WEAPON01 = 14,
	ENCHANTSCROLL_WEAPON02 = 15,
	ENCHANTSCROLL_ARMOR01 = 16,
	ENCHANTSCROLL_ARMOR02 = 17,
	ENCHANTSCROLL_ACCESSARY01 = 18,
	ENCHANTSCROLL_ACCESSARY02 = 19,
	ESSENCE_IELO = 20,
	TITANSTONE01 = 21,
	TITANSTONE02 = 22,
	TITANSTONE03 = 23,
	TITANSTONE04 = 24,
	TITANSTONE05 = 25,
	EXP_WEAPON01 = 26,
	EXP_ARMOR01 = 27,
	EXP_PANTS01 = 28,
	EXP_ACCESSARY01 = 29,
	TITAN_STONE = 30,
	SWEEP_TICKET = 31,
	HERO_UPGRADEMATERIAL = 32,
	ITEM_OPTIONRESETMATERIAL = 33,
	ITEM_UPGRADEMATERIAL = 34,
	SUMMONTICKET01 = 35,
	SUMMONTICKET02 = 36,
	FLOORCOIN05 = 37,
	FLOORCOIN06 = 38,
	FLOORCOIN07 = 39,
	FLOORCOIN08 = 40,
	FLOORCOIN09 = 41,
	FLOORCOIN10 = 42,
	FLOORCOIN11 = 43,
	FLOORCOIN12 = 44,
	FLOORCOIN13 = 45,
	FLOORCOIN14 = 46,
	FLOORCOIN15 = 47,
	FLOORCOIN16 = 48,
	FLOORCOIN17 = 49,
	FLOORCOIN18 = 50,
	FLOORCOIN19 = 51,
	FLOORCOIN20 = 52,
	FLOORCOIN21 = 53,
	FLOORCOIN22 = 54,
	FLOORCOIN23 = 55,
	FLOORCOIN24 = 56,
	FLOORSTORETICKET = 57,
	MISSION_ADD_SCROLL = 58,
	MISSION_ADD_SCROLL_FREE = 59,
	ITEM_UPGRADEMATERIAL02 = 60,
	CASH_KRW = 61,
	CASH_USD = 62,
};

UENUM(BlueprintType)
enum class EWALLET_TYPE2 : uint8
{
	ARENA_DAILYBONUSTOKEN = 0,
	ARENA_DEFENDERRESETTOKEN = 1,
	MIRROR_DEFENDERRESET_FREE = 2,
	MIRROR_ENTRANCE = 3,
	FLOORSTORE_RESETTOKEN = 4,
	FLOORSTORE_RESETTOKEN_GEM = 5,
	TIMETREASURE_GOLD = 6,
	TIMETREASURE_HERORUNE = 7,
	TIMETREASURE_AVATAR_EXP = 8,
	TIMETREASURE_EQUIP = 9,
	TIMETREASURE_RUNE = 10,
	ITEM_INVENTORY_SLOT_TOKEN = 11,
	HERO_INVENTORY_SLOT_TOKEN = 12,
	S_AKHAN_EASY = 13,
	S_AKHAN_NORMAL = 14,
	S_AKHAN_HARD = 15,
	S_AKHAN_VERYHARD = 16,
	S_GIGANT_EASY = 17,
	S_GIGANT_NORMAL = 18,
	S_GIGANT_HARD = 19,
	S_GIGANT_VERYHARD = 20,
	S_MORS_EASY = 21,
	S_MORS_NORMAL = 22,
	S_MORS_HARD = 23,
	S_MORS_VERYHARD = 24,
	S_TOWERBOSS_F1 = 25,
	S_TOWERBOSS_F2 = 26,
	S_TOWERBOSS_F3 = 27,
	S_TOWERBOSS_F4 = 28,
	S_TOWERBOSS_F5 = 29,
	S_TOWERBOSS_F6 = 30,
	S_TOWERBOSS_F7 = 31,
	S_TOWERBOSS_F8 = 32,
	S_TOWERBOSS_F9 = 33,
	S_TOWERBOSS_F10 = 34,
	S_TOWERBOSS_F11 = 35,
	S_TOWERBOSS_F12 = 36,
	S_TOWERBOSS_F13 = 37,
	S_TOWERBOSS_F14 = 38,
	S_TOWERBOSS_F15 = 39,
	S_TOWERBOSS_F16 = 40,
	S_TOWERBOSS_F17 = 41,
	S_TOWERBOSS_F18 = 42,
	S_TOWERBOSS_F19 = 43,
	S_TOWERBOSS_F20 = 44,
	S_TOWERBOSS_F21 = 45,
	S_TOWERBOSS_F22 = 46,
	S_TOWERBOSS_F23 = 47,
	S_TOWERBOSS_F24 = 48,
	S_TOWERBOSS_F25 = 49,
};

UENUM(BlueprintType)
enum class EWALLET_TYPE3 : uint8
{
	RUNE001 = 0,
	RUNE002 = 1,
	RUNE003 = 2,
	RUNE004 = 3,
	RUNE005 = 4,
	RUNE006 = 5,
	RUNE007 = 6,
	RUNE008 = 7,
	RUNE009 = 8,
	RUNE010 = 9,
	RUNE011 = 10,
	RUNE012 = 11,
	RUNE013 = 12,
	RUNE014 = 13,
	RUNE015 = 14,
	RUNE016 = 15,
	RUNE017 = 16,
	RUNE018 = 17,
	RUNE019 = 18,
	RUNE020 = 19,
	POTION = 20,
	BOOSTER = 21,
	HEROPIECE_AGATHON03 = 22,
	HEROPIECE_AGATHON04 = 23,
	HEROPIECE_AGATHON05 = 24,
	HEROPIECE_RAYNA03 = 25,
	HEROPIECE_RAYNA04 = 26,
	HEROPIECE_RAYNA05 = 27,
	HEROPIECE_YOSEPH03 = 28,
	HEROPIECE_YOSEPH04 = 29,
	HEROPIECE_YOSEPH05 = 30,
	HEROPIECE_THAN03 = 31,
	HEROPIECE_THAN04 = 32,
	HEROPIECE_THAN05 = 33,
	HEROPIECE_AMON03 = 34,
	HEROPIECE_AMON04 = 35,
	HEROPIECE_AMON05 = 36,
	HEROPIECE_MOMENT03 = 37,
	HEROPIECE_MOMENT04 = 38,
	HEROPIECE_MOMENT05 = 39,
	HEROPIECE_SIRIA03 = 40,
	HEROPIECE_SIRIA04 = 41,
	HEROPIECE_SIRIA05 = 42,
	HEROPIECE_BALT03 = 43,
	HEROPIECE_BALT04 = 44,
	HEROPIECE_BALT05 = 45,
	HEROPIECE_GRANT03 = 46,
	HEROPIECE_GRANT04 = 47,
	HEROPIECE_GRANT05 = 48,
	HEROPIECE_FLAME03 = 49,
	HEROPIECE_FLAME04 = 50,
	HEROPIECE_FLAME05 = 51,
	HEROPIECE_LUCY03 = 52,
	HEROPIECE_LUCY04 = 53,
	HEROPIECE_LUCY05 = 54,
	HEROPIECE_SOPHIA03 = 55,
	HEROPIECE_SOPHIA04 = 56,
	HEROPIECE_SOPHIA05 = 57,
	HEROPIECE_BARTOR03 = 58,
	HEROPIECE_BARTOR04 = 59,
	HEROPIECE_BARTOR05 = 60,
	HEROPIECE_RHEA03 = 61,
	HEROPIECE_RHEA04 = 62,
	HEROPIECE_RHEA05 = 63,
	HEROPIECE_DOROTHY03 = 64,
	HEROPIECE_DOROTHY04 = 65,
	HEROPIECE_DOROTHY05 = 66,
	HEROPIECE_SCARLET03 = 67,
	HEROPIECE_SCARLET04 = 68,
	HEROPIECE_SCARLET05 = 69,
	HEROPIECE_JIN03 = 70,
	HEROPIECE_JIN04 = 71,
	HEROPIECE_JIN05 = 72,
	HEROPIECE_BANTONIO03 = 73,
	HEROPIECE_BANTONIO04 = 74,
	HEROPIECE_BANTONIO05 = 75,
	HEROPIECE_KRATOS03 = 76,
	HEROPIECE_KRATOS04 = 77,
	HEROPIECE_KRATOS05 = 78,
	HEROPIECE_PANG03 = 79,
	HEROPIECE_PANG04 = 80,
	HEROPIECE_PANG05 = 81,
	HEROPIECE_SHARON03 = 82,
	HEROPIECE_SHARON04 = 83,
	HEROPIECE_SHARON05 = 84,
	HEROPIECE_BARD03 = 85,
	HEROPIECE_BARD04 = 86,
	HEROPIECE_BARD05 = 87,
	HEROPIECE_BUDDY03 = 88,
	HEROPIECE_BUDDY04 = 89,
	HEROPIECE_BUDDY05 = 90,
	HEROPIECE_TIERA03 = 91,
	HEROPIECE_TIERA04 = 92,
	HEROPIECE_TIERA05 = 93,
	HEROPIECE_ZAGAN03 = 94,
	HEROPIECE_ZAGAN04 = 95,
	HEROPIECE_ZAGAN05 = 96,
	HEROPIECE_BELITA03 = 97,
	HEROPIECE_BELITA04 = 98,
	HEROPIECE_BELITA05 = 99,
	HEROPIECE_BONNIE03 = 100,
	HEROPIECE_BONNIE04 = 101,
	HEROPIECE_BONNIE05 = 102,
	HEROPIECE_IOLA03 = 103,
	HEROPIECE_IOLA04 = 104,
	HEROPIECE_IOLA05 = 105,
	HEROPIECE_MURMUR03 = 106,
	HEROPIECE_MURMUR04 = 107,
	HEROPIECE_MURMUR05 = 108,
	HEROPIECE_RANDOM_ALL = 109,
	HEROPIECE_RANDOM_CONTINENT_TANKER03 = 110,
	HEROPIECE_RANDOM_CONTINENT_TANKER04 = 111,
	HEROPIECE_RANDOM_CONTINENT_TANKER05 = 112,
	HEROPIECE_RANDOM_CONTINENT_MELEEDEALER03 = 113,
	HEROPIECE_RANDOM_CONTINENT_MELEEDEALER04 = 114,
	HEROPIECE_RANDOM_CONTINENT_MELEEDEALER05 = 115,
	HEROPIECE_RANDOM_CONTINENT_RANGEDEALER03 = 116,
	HEROPIECE_RANDOM_CONTINENT_RANGEDEALER04 = 117,
	HEROPIECE_RANDOM_CONTINENT_RANGEDEALER05 = 118,
	HEROPIECE_RANDOM_CONTINENT_MAGICDEALER03 = 119,
	HEROPIECE_RANDOM_CONTINENT_MAGICDEALER04 = 120,
	HEROPIECE_RANDOM_CONTINENT_MAGICDEALER05 = 121,
	HEROPIECE_RANDOM_CONTINENT_SUPPORTER03 = 122,
	HEROPIECE_RANDOM_CONTINENT_SUPPORTER04 = 123,
	HEROPIECE_RANDOM_CONTINENT_SUPPORTER05 = 124,
	HEROPIECE_RANDOM_CLASS_LUX03 = 125,
	HEROPIECE_RANDOM_CLASS_LUX04 = 126,
	HEROPIECE_RANDOM_CLASS_LUX05 = 127,
	HEROPIECE_RANDOM_CLASS_SOLONA03 = 128,
	HEROPIECE_RANDOM_CLASS_SOLONA04 = 129,
	HEROPIECE_RANDOM_CLASS_SOLONA05 = 130,
	HEROPIECE_RANDOM_CLASS_LUNA03 = 131,
	HEROPIECE_RANDOM_CLASS_LUNA04 = 132,
	HEROPIECE_RANDOM_CLASS_LUNA05 = 133,
	HEROPIECE_RANDOM_CLASS_NOX03 = 134,
	HEROPIECE_RANDOM_CLASS_NOX04 = 135,
	HEROPIECE_RANDOM_CLASS_NOX05 = 136,
	HEROPIECE_RANDOM_GRADE_LUX_TANKER = 137,
	HEROPIECE_RANDOM_GRADE_LUX_MELEEDEALER = 138,
	HEROPIECE_RANDOM_GRADE_LUX_RANGEDEALER = 139,
	HEROPIECE_RANDOM_GRADE_LUX_MAGICDEALER = 140,
	HEROPIECE_RANDOM_GRADE_LUX_SUPPORTER = 141,
	HEROPIECE_RANDOM_GRADE_SOLONA_TANKER = 142,
	HEROPIECE_RANDOM_GRADE_SOLONA_MELEEDEALER = 143,
	HEROPIECE_RANDOM_GRADE_SOLONA_RANGEDEALER = 144,
	HEROPIECE_RANDOM_GRADE_SOLONA_MAGICDEALER = 145,
	HEROPIECE_RANDOM_GRADE_SOLONA_SUPPORTER = 146,
	HEROPIECE_RANDOM_GRADE_LUNA_TANKER = 147,
	HEROPIECE_RANDOM_GRADE_LUNA_MELEEDEALER = 148,
	HEROPIECE_RANDOM_GRADE_LUNA_RANGEDEALER = 149,
	HEROPIECE_RANDOM_GRADE_LUNA_MAGICDEALER = 150,
	HEROPIECE_RANDOM_GRADE_LUNA_SUPPORTER = 151,
	HEROPIECE_RANDOM_GRADE_NOX_TANKER = 152,
	HEROPIECE_RANDOM_GRADE_NOX_MELEEDEALER = 153,
	HEROPIECE_RANDOM_GRADE_NOX_RANGEDEALER = 154,
	HEROPIECE_RANDOM_GRADE_NOX_MAGICDEALER = 155,
	HEROPIECE_RANDOM_GRADE_NOX_SUPPORTER = 156,
	HEROPIECE_RANDOM_CONTIGRADE_TANKER = 157,
	HEROPIECE_RANDOM_CONTIGRADE_MELEEDEALER = 158,
	HEROPIECE_RANDOM_CONTIGRADE_RANGEDEALER = 159,
	HEROPIECE_RANDOM_CONTIGRADE_MAGICDEALER = 160,
	HEROPIECE_RANDOM_CONTIGRADE_SUPPORTER = 161,
	HEROPIECE_RANDOM_CONTICLASS_03 = 162,
	HEROPIECE_RANDOM_CONTICLASS_04 = 163,
	HEROPIECE_RANDOM_CONTICLASS_05 = 164,
	HEROPIECE_RANDOM_CLASSGRADE_LUX = 165,
	HEROPIECE_RANDOM_CLASSGRADE_SOLONA = 166,
	HEROPIECE_RANDOM_CLASSGRADE_LUNA = 167,
	HEROPIECE_RANDOM_CLASSGRADE_NOX = 168,
};

